export * from './molecules'
export { default as IdentifierDetail } from './organisms/identifier-detail'
export { default as CollapsibleDetailCollection } from './organisms/collapsible-detail-collection'
export { IDetailViewProps, DetailViewComponent } from './atoms/detail-view-component'
export { CollapsibleDetailCollectionProps, useDetailViewType } from './organisms/collapsible-detail-collection'
