import * as BRAND from './nhs-colours'

export const PRIMARY_TEXT_COLOUR = BRAND.NHS_BLACK
export const SECONDARY_TEXT_COLOUR = BRAND.NHS_MID_GREY
export const DANGER_TEXT_COLOUR = BRAND.NHS_DARK_RED
export const INFO_TEXT_COLOUR = BRAND.NHS_DARK_BLUE

export const ICON_RED_COLOUR = BRAND.NHS_EMERGENCY_SERVICES_RED
export const ICON_AMBER_COLOUR = BRAND.NHS_ORANGE
export const ICON_GREEN_COLOUR = BRAND.NHS_GREEN
