export const MOBILE_MAXIMUM_MEDIA_QUERY = '@media only screen and (max-width: 767px)'
export const TABLET_MINIMUM_MEDIA_QUERY = '@media only screen and (min-width: 768px)'
export const TABLET_ONLY_MEDIA_QUERY = '@media only screen and (min-width: 768px) and (max-width: 1023px)'
export const DESKTOP_MINIMUM_MEDIA_QUERY = '@media only screen and (min-width: 1024px)'
export const DESKTOP_ONLY_MEDIA_QUERY = '@media only screen and (min-width: 1024px) and (max-width: 1199px)'
export const WIDESCREEN_MINIMUM_MEDIA_QUERY = '@media only screen and (min-width: 1200px)'
