name: lerna-version

on:
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Config CI Git User
        run: |
            git config --global user.name '@ltht-epr'
            git config --global user.email 'leedsth-tr.ppmlead@nhs.net'
          env:
            GITHUB_PAT: ${{ secrets.ACTION_PAT }}

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install packages
          run: yarn

      - name: Update package versions
          run: yarn new:version
          env:
            GITHUB_PAT: ${{ secrets.ACTION_PAT }}
