name: lerna-version

on:
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install packages
          run: yarn

      - name: Update package versions
          run: yarn new:version