import { TableData } from '@ltht-react/table'

export const mockTableData: TableData = {
  headers: [
    {
      type: 'accessor',
      id: 'answerset',
      cellProps: { text: '' },
    },
    {
      type: 'accessor',
      id: 'question1',
      cellProps: { text: 'First Question' },
    },
    {
      type: 'accessor',
      id: 'question2',
      cellProps: { text: 'Second Question' },
    },
  ],
  rows: [
    {
      answerset: { text: 'First Answer Set' },
      question1: { text: 'Answer 1 (set1)' },
      question2: { text: 'Answer 2 (set1)' },
    },
    {
      answerset: { text: 'Second Answer Set' },
      question1: { text: 'Answer 1 (set2)' },
      question2: { text: 'Answer 2 (set2)' },
    },
  ],
}

export const mockTableDataWithSubheaders: TableData = {
  headers: [
    {
      type: 'accessor',
      id: 'answerset',
      cellProps: { text: '' },
    },
    {
      type: 'accessor',
      id: 'question1',
      cellProps: { text: 'First Question' },
    },
    {
      type: 'group',
      id: 'questiongroup1',
      cellProps: { text: 'Question Group' },
      subHeaders: [
        {
          type: 'accessor',
          id: 'question2',
          cellProps: { text: 'Second Question' },
        },
        {
          type: 'accessor',
          id: 'question3',
          cellProps: { text: 'Third Question' },
        },
      ],
    },
  ],
  rows: [
    {
      answerset: { text: 'First Answer Set' },
      question1: { text: 'Answer 1 (set1)' },
      question2: { text: 'Answer 2 (set1)' },
      question3: { text: 'Answer 3 (set1)' },
    },
    {
      answerset: { text: 'Second Answer Set' },
      question1: { text: 'Answer 1 (set2)' },
      question2: { text: 'Answer 2 (set2)' },
      question3: { text: 'Answer 3 (set2)' },
    },
  ],
}

export const mockTableDataWithSubrows: TableData = {
  headers: [
    {
      type: 'accessor',
      id: 'answerset',
      cellProps: { text: '' },
    },
    {
      type: 'accessor',
      id: 'question1',
      cellProps: { text: 'First Question' },
    },
    {
      type: 'accessor',
      id: 'question2',
      cellProps: { text: 'Second Question' },
    },
  ],
  rows: [
    {
      answerset: { text: 'First Answer Set' },
      question1: { text: 'Answer 1 (set1)' },
      question2: { text: 'Answer 2 (set1)' },
    },
    {
      answerset: { text: 'Second Answer Set' },
      question1: { text: 'Answer 1 (set2)' },
      question2: { text: 'Answer 2 (set2)' },
      subRows: [
        {
          question1: { text: 'Sub answer 1 (set2)' },
          question2: { text: 'Sub answer 2 (set2)' },
        },
      ],
    },
  ],
}

const customComponent = <button type="button">This cell is customised</button>

export const mockTableDataWithCustomComponent: TableData = {
  headers: [
    {
      type: 'accessor',
      id: 'answerset',
      cellProps: { text: '' },
    },
    {
      type: 'accessor',
      id: 'question1',
      cellProps: { text: 'First Question' },
    },
    {
      type: 'accessor',
      id: 'question2',
      cellProps: { text: 'Second Question' },
    },
  ],
  rows: [
    {
      answerset: { text: 'First Answer Set' },
      question1: { customComponentOverride: customComponent },
      question2: { text: 'Answer 2 (set1)' },
    },
    {
      answerset: { text: 'Second Answer Set' },
      question1: { text: 'Answer 1 (set2)' },
      question2: { text: 'Answer 2 (set2)' },
    },
  ],
}

export const mockTableDataForPagination: TableData = {
  headers: [
    { type: 'accessor', id: 'name', cellProps: { text: 'Name' } },
    { type: 'accessor', id: 'question1', cellProps: { text: 'Home Town' } },
    { type: 'accessor', id: 'question2', cellProps: { text: 'Date of Birth' } },
    { type: 'accessor', id: 'question3', cellProps: { text: 'Favourite Color' } },
    { type: 'accessor', id: 'question4', cellProps: { text: 'Phone' } },
  ],
  rows: [
    {
      name: { text: 'Kim Barton' },
      question1: { text: 'Euclid' },
      question2: { text: 'Sun Mar 05 1989' },
      question3: { text: 'green' },
      question4: { text: '312-988-8045' },
    },
    {
      name: { text: 'Vicki Tremblay' },
      question1: { text: 'Hacienda Heights' },
      question2: { text: 'Tue Apr 03 1962' },
      question3: { text: 'teal' },
      question4: { text: '1-510-449-9243 x744' },
    },
    {
      name: { text: 'Gilberto Carter' },
      question1: { text: 'Santa Barbara' },
      question2: { text: 'Thu Feb 24 1966' },
      question3: { text: 'green' },
      question4: { text: '1-256-785-3195 x06294' },
    },
    {
      name: { text: 'Delia Schiller' },
      question1: { text: 'Barnstable Town' },
      question2: { text: 'Mon May 13 1963' },
      question3: { text: 'lavender' },
      question4: { text: '(346) 297-6466 x589' },
    },
    {
      name: { text: 'Dwayne Ritchie DDS' },
      question1: { text: 'Honolulu' },
      question2: { text: 'Wed Jan 27 1960' },
      question3: { text: 'blue' },
      question4: { text: '713-407-4666 x81001' },
    },
    {
      name: { text: 'Patrick Rath' },
      question1: { text: 'Sparks' },
      question2: { text: 'Sat Sep 19 1987' },
      question3: { text: 'magenta' },
      question4: { text: '(315) 437-3535' },
    },
    {
      name: { text: 'Alyssa Tillman V' },
      question1: { text: 'Coachella' },
      question2: { text: 'Sun Aug 10 1986' },
      question3: { text: 'indigo' },
      question4: { text: '1-482-641-9948 x68035' },
    },
    {
      name: { text: 'Velma Veum' },
      question1: { text: 'Ashburn' },
      question2: { text: 'Mon Dec 06 1999' },
      question3: { text: 'maroon' },
      question4: { text: '1-210-388-4533 x274' },
    },
    {
      name: { text: 'Mr. Alton Feil' },
      question1: { text: 'Rialto' },
      question2: { text: 'Mon Jul 27 1953' },
      question3: { text: 'turquoise' },
      question4: { text: '930-303-4790 x50408' },
    },
    {
      name: { text: 'Alvin Kuhlman' },
      question1: { text: 'Hampton' },
      question2: { text: 'Tue Dec 06 1949' },
      question3: { text: 'pink' },
      question4: { text: '894-419-3397 x334' },
    },
    {
      name: { text: 'Brett Grady' },
      question1: { text: 'Amarillo' },
      question2: { text: 'Sun Mar 30 1997' },
      question3: { text: 'turquoise' },
      question4: { text: '336.933.0969' },
    },
    {
      name: { text: 'Jessie Spencer' },
      question1: { text: 'Brownsville' },
      question2: { text: 'Sat Sep 26 1998' },
      question3: { text: 'indigo' },
      question4: { text: '(537) 903-4424 x26411' },
    },
    {
      name: { text: 'Flora Quigley' },
      question1: { text: 'Alhambra' },
      question2: { text: 'Thu Apr 18 1946' },
      question3: { text: 'red' },
      question4: { text: '1-830-783-7161 x6790' },
    },
    {
      name: { text: 'Krista Rowe' },
      question1: { text: 'Lake Forest' },
      question2: { text: 'Tue Jun 04 1996' },
      question3: { text: 'indigo' },
      question4: { text: '1-618-815-9095' },
    },
    {
      name: { text: 'Neil Graham' },
      question1: { text: 'Parker' },
      question2: { text: 'Sun Aug 28 1966' },
      question3: { text: 'lime' },
      question4: { text: '1-846-632-0849' },
    },
    {
      name: { text: 'Mr. Horace Ernser III' },
      question1: { text: 'Casa Grande' },
      question2: { text: 'Mon Sep 06 1999' },
      question3: { text: 'purple' },
      question4: { text: '1-715-614-9384 x367' },
    },
    {
      name: { text: 'Wade Hirthe' },
      question1: { text: 'Norwalk' },
      question2: { text: 'Sat May 19 1945' },
      question3: { text: 'plum' },
      question4: { text: '(931) 532-0585' },
    },
    {
      name: { text: 'Leslie Parker' },
      question1: { text: 'St. Charles' },
      question2: { text: 'Thu Jan 30 1947' },
      question3: { text: 'indigo' },
      question4: { text: '1-375-948-4364 x88260' },
    },
    {
      name: { text: 'Erma Daniel' },
      question1: { text: 'Valdosta' },
      question2: { text: 'Sun Oct 12 1947' },
      question3: { text: 'sky blue' },
      question4: { text: '1-872-915-7420 x7269' },
    },
    {
      name: { text: 'Ross Hodkiewicz' },
      question1: { text: 'Whittier' },
      question2: { text: 'Thu Mar 12 1942' },
      question3: { text: 'purple' },
      question4: { text: '1-774-582-7411 x462' },
    },
    {
      name: { text: 'Melanie Hansen' },
      question1: { text: 'Redwood City' },
      question2: { text: 'Sun Jan 26 1975' },
      question3: { text: 'salmon' },
      question4: { text: '1-351-975-4935 x114' },
    },
    {
      name: { text: 'Michele Bartell' },
      question1: { text: 'Milpitas' },
      question2: { text: 'Mon Nov 20 1950' },
      question3: { text: 'cyan' },
      question4: { text: '(255) 314-3639' },
    },
    {
      name: { text: 'Jason Johns' },
      question1: { text: 'Hattiesburg' },
      question2: { text: 'Wed Feb 22 1961' },
      question3: { text: 'sky blue' },
      question4: { text: '872.699.9854 x5142' },
    },
    {
      name: { text: 'Reginald Johnson PhD' },
      question1: { text: 'Reading' },
      question2: { text: 'Wed Jun 23 1982' },
      question3: { text: 'yellow' },
      question4: { text: '(220) 869-9748' },
    },
    {
      name: { text: 'Randall Cummings DVM' },
      question1: { text: 'Ashburn' },
      question2: { text: 'Mon Feb 28 1977' },
      question3: { text: 'indigo' },
      question4: { text: '758-976-4624 x642' },
    },
    {
      name: { text: 'Bob Labadie' },
      question1: { text: 'Centennial' },
      question2: { text: 'Sun Aug 29 1948' },
      question3: { text: 'ivory' },
      question4: { text: '462-995-9740 x8188' },
    },
    {
      name: { text: 'Marion Gorczany' },
      question1: { text: 'Pawtucket' },
      question2: { text: 'Sat Sep 28 2002' },
      question3: { text: 'yellow' },
      question4: { text: '271.707.4519 x8428' },
    },
    {
      name: { text: 'Deborah Jast I' },
      question1: { text: 'Arcadia' },
      question2: { text: 'Wed Jul 28 1971' },
      question3: { text: 'salmon' },
      question4: { text: '(907) 976-5079' },
    },
    {
      name: { text: 'Alfred Kemmer' },
      question1: { text: 'Beaverton' },
      question2: { text: 'Tue Aug 11 1992' },
      question3: { text: 'fuchsia' },
      question4: { text: '946.368.6837 x5069' },
    },
    {
      name: { text: 'Woodrow Greenfelder' },
      question1: { text: 'Biloxi' },
      question2: { text: 'Sun Oct 09 1983' },
      question3: { text: 'violet' },
      question4: { text: '1-773-349-5973 x92925' },
    },
    {
      name: { text: 'Georgia Pfannerstill' },
      question1: { text: 'Jacksonville' },
      question2: { text: 'Sun Nov 16 1997' },
      question3: { text: 'grey' },
      question4: { text: '(522) 237-9099 x193' },
    },
    {
      name: { text: 'Darren Collins IV' },
      question1: { text: 'Wilmington' },
      question2: { text: 'Tue Jan 04 1977' },
      question3: { text: 'indigo' },
      question4: { text: '1-819-477-0421 x0994' },
    },
    {
      name: { text: 'Ms. Sarah Davis' },
      question1: { text: 'Caguas' },
      question2: { text: 'Sat Sep 01 1951' },
      question3: { text: 'violet' },
      question4: { text: '643-779-1176 x3774' },
    },
    {
      name: { text: 'Cora Zboncak' },
      question1: { text: 'Overland Park' },
      question2: { text: 'Tue May 15 1984' },
      question3: { text: 'magenta' },
      question4: { text: '(927) 381-3695' },
    },
    {
      name: { text: 'Shelia Huel III' },
      question1: { text: 'Gardena' },
      question2: { text: 'Sun Nov 24 1985' },
      question3: { text: 'gold' },
      question4: { text: '395-424-0606 x196' },
    },
    {
      name: { text: 'Lorene Friesen I' },
      question1: { text: 'Greenwood' },
      question2: { text: 'Sat Oct 18 1947' },
      question3: { text: 'indigo' },
      question4: { text: '(655) 284-0346' },
    },
    {
      name: { text: 'Mr. Carol Wyman' },
      question1: { text: 'Federal Way' },
      question2: { text: 'Sat Jul 31 1971' },
      question3: { text: 'olive' },
      question4: { text: '769.940.8515 x40671' },
    },
    {
      name: { text: 'Hugh Lang' },
      question1: { text: 'West Hartford' },
      question2: { text: 'Tue May 18 1948' },
      question3: { text: 'salmon' },
      question4: { text: '1-337-966-7073 x320' },
    },
    {
      name: { text: 'Julio Weimann' },
      question1: { text: 'Santa Maria' },
      question2: { text: 'Mon Oct 10 1994' },
      question3: { text: 'red' },
      question4: { text: '(780) 465-3312 x7461' },
    },
    {
      name: { text: 'Linda Beatty V' },
      question1: { text: 'Tamiami' },
      question2: { text: 'Wed Mar 23 1955' },
      question3: { text: 'violet' },
      question4: { text: '821-292-8092 x1714' },
    },
    {
      name: { text: 'Jay Ritchie' },
      question1: { text: 'Tempe' },
      question2: { text: 'Fri Sep 28 2001' },
      question3: { text: 'lime' },
      question4: { text: '(866) 934-7328 x865' },
    },
    {
      name: { text: 'Todd Simonis' },
      question1: { text: 'Cerritos' },
      question2: { text: 'Mon Sep 22 1958' },
      question3: { text: 'fuchsia' },
      question4: { text: '(350) 705-8108 x8761' },
    },
    {
      name: { text: 'Amelia Miller' },
      question1: { text: 'Hammond' },
      question2: { text: 'Fri Mar 21 1986' },
      question3: { text: 'white' },
      question4: { text: '(928) 518-6283 x6572' },
    },
    {
      name: { text: 'Kenneth Miller' },
      question1: { text: 'Huntington' },
      question2: { text: 'Sat May 10 1997' },
      question3: { text: 'olive' },
      question4: { text: '335-344-5077 x31015' },
    },
    {
      name: { text: 'Orville Swift V' },
      question1: { text: 'St. Cloud' },
      question2: { text: 'Mon Jan 28 1963' },
      question3: { text: 'lavender' },
      question4: { text: '1-847-998-1633' },
    },
    {
      name: { text: 'Norma Howell' },
      question1: { text: 'Clarksville' },
      question2: { text: 'Tue Apr 15 1997' },
      question3: { text: 'orchid' },
      question4: { text: '(259) 457-2747 x80446' },
    },
    {
      name: { text: 'Lola Tillman' },
      question1: { text: 'Coon Rapids' },
      question2: { text: 'Mon Sep 24 1962' },
      question3: { text: 'salmon' },
      question4: { text: '(627) 202-6668' },
    },
    {
      name: { text: 'Lydia Ferry' },
      question1: { text: 'Allen' },
      question2: { text: 'Sat May 06 1961' },
      question3: { text: 'ivory' },
      question4: { text: '1-592-277-6405' },
    },
    {
      name: { text: 'Andres Bernhard' },
      question1: { text: 'Paradise' },
      question2: { text: 'Sat Apr 04 1964' },
      question3: { text: 'lime' },
      question4: { text: '281-256-3101 x87188' },
    },
    {
      name: { text: 'Cathy Kihn' },
      question1: { text: 'Glenview' },
      question2: { text: 'Fri Sep 10 1999' },
      question3: { text: 'orchid' },
      question4: { text: '839-526-5056' },
    },
  ],
}

export const mockTableDataForVerticalPagination: TableData = {
  headers: [
    { type: 'accessor', id: 'property', cellProps: { text: '' } },
    { type: 'accessor', id: 'col-1', cellProps: { text: 'Orlo' } },
    { type: 'accessor', id: 'col-2', cellProps: { text: 'Eula' } },
    { type: 'accessor', id: 'col-3', cellProps: { text: 'Jaqueline' } },
    { type: 'accessor', id: 'col-4', cellProps: { text: 'Holden' } },
    { type: 'accessor', id: 'col-5', cellProps: { text: 'Manuel' } },
    { type: 'accessor', id: 'col-6', cellProps: { text: 'Brad' } },
    { type: 'accessor', id: 'col-7', cellProps: { text: 'Carli' } },
    { type: 'accessor', id: 'col-8', cellProps: { text: 'Easton' } },
    { type: 'accessor', id: 'col-9', cellProps: { text: 'Lavern' } },
    { type: 'accessor', id: 'col-10', cellProps: { text: 'Abigayle' } },
    { type: 'accessor', id: 'col-11', cellProps: { text: 'Devante' } },
    { type: 'accessor', id: 'col-12', cellProps: { text: 'Gerda' } },
    { type: 'accessor', id: 'col-13', cellProps: { text: 'Susan' } },
    { type: 'accessor', id: 'col-14', cellProps: { text: 'Beryl' } },
    { type: 'accessor', id: 'col-15', cellProps: { text: 'Emmet' } },
    { type: 'accessor', id: 'col-16', cellProps: { text: 'Joany' } },
    { type: 'accessor', id: 'col-17', cellProps: { text: 'Cory' } },
    { type: 'accessor', id: 'col-18', cellProps: { text: 'Lue' } },
    { type: 'accessor', id: 'col-19', cellProps: { text: 'Osbaldo' } },
    { type: 'accessor', id: 'col-20', cellProps: { text: 'Maryjane' } },
  ],
  rows: [
    {
      property: {
        customComponentOverride: <b>Favourite Colour?</b>,
      },
      'col-1': { text: 'salmon' },
      'col-2': { text: 'pink' },
      'col-3': { text: 'orange' },
      'col-4': { text: 'orchid' },
      'col-5': { text: 'indigo' },
      'col-6': { text: 'teal' },
      'col-7': { text: 'red' },
      'col-8': { text: 'mint green' },
      'col-9': { text: 'azure' },
      'col-10': { text: 'white' },
      'col-11': { text: 'violet' },
      'col-12': { text: 'lavender' },
      'col-13': { text: 'lime' },
      'col-14': { text: 'orchid' },
      'col-15': { text: 'tan' },
      'col-16': { text: 'pink' },
      'col-17': { text: 'salmon' },
      'col-18': { text: 'maroon' },
      'col-19': { text: 'indigo' },
      'col-20': { text: 'purple' },
    },
    {
      property: {
        customComponentOverride: <b>Favourite Car Brand?</b>,
      },
      'col-1': { text: 'Cadillac' },
      'col-2': { text: 'Audi' },
      'col-3': { text: 'Mercedes Benz' },
      'col-4': { text: 'Bugatti' },
      'col-5': { text: 'Jeep' },
      'col-6': { text: 'Rolls Royce' },
      'col-7': { text: 'Fiat' },
      'col-8': { text: 'Bugatti' },
      'col-9': { text: 'Mazda' },
      'col-10': { text: 'Mercedes Benz' },
      'col-11': { text: 'Bugatti' },
      'col-12': { text: 'Nissan' },
      'col-13': { text: 'Mazda' },
      'col-14': { text: 'Bentley' },
      'col-15': { text: 'Ford' },
      'col-16': { text: 'Volkswagen' },
      'col-17': { text: 'Aston Martin' },
      'col-18': { text: 'Mini' },
      'col-19': { text: 'Hyundai' },
      'col-20': { text: 'Lamborghini' },
    },
    {
      property: {
        customComponentOverride: <b>Favourite Animal?</b>,
      },
      'col-1': { text: 'cetacean' },
      'col-2': { text: 'crocodilia' },
      'col-3': { text: 'bear' },
      'col-4': { text: 'rabbit' },
      'col-5': { text: 'bear' },
      'col-6': { text: 'cow' },
      'col-7': { text: 'lion' },
      'col-8': { text: 'horse' },
      'col-9': { text: 'dog' },
      'col-10': { text: 'dog' },
      'col-11': { text: 'cat' },
      'col-12': { text: 'cow' },
      'col-13': { text: 'crocodilia' },
      'col-14': { text: 'crocodilia' },
      'col-15': { text: 'crocodilia' },
      'col-16': { text: 'insect' },
      'col-17': { text: 'cow' },
      'col-18': { text: 'horse' },
      'col-19': { text: 'cetacean' },
      'col-20': { text: 'bird' },
    },
    {
      property: {
        customComponentOverride: <b>Favourite Country Visited?</b>,
      },
      'col-1': { text: 'Lesotho' },
      'col-2': { text: 'Morocco' },
      'col-3': { text: 'Botswana' },
      'col-4': { text: 'United States' },
      'col-5': { text: 'United Kingdom' },
      'col-6': { text: 'Bahamas' },
      'col-7': { text: 'Czech Republic' },
      'col-8': { text: 'Nauru' },
      'col-9': { text: 'Virgin Islands' },
      'col-10': { text: 'Martinique' },
      'col-11': { text: 'Pakistan' },
      'col-12': { text: 'San Marino' },
      'col-13': { text: 'Mozambique' },
      'col-14': { text: 'Spain' },
      'col-15': { text: 'Armenia' },
      'col-16': { text: 'Gambia' },
      'col-17': { text: 'Isle of Man' },
      'col-18': { text: 'Indonesia' },
      'col-19': { text: 'Palau' },
      'col-20': { text: 'Benin' },
    },
    {
      property: {
        customComponentOverride: <b>Favourite City?</b>,
      },
      'col-1': { text: 'Euless' },
      'col-2': { text: 'Fishers' },
      'col-3': { text: 'Richardson' },
      'col-4': { text: 'Salem' },
      'col-5': { text: 'Redlands' },
      'col-6': { text: 'Redding' },
      'col-7': { text: 'New Bedford' },
      'col-8': { text: 'Federal Way' },
      'col-9': { text: 'Sunnyvale' },
      'col-10': { text: 'Blacksburg' },
      'col-11': { text: 'Irving' },
      'col-12': { text: 'Summerville' },
      'col-13': { text: 'Merced' },
      'col-14': { text: 'Westland' },
      'col-15': { text: 'Noblesville' },
      'col-16': { text: 'Davenport' },
      'col-17': { text: 'Palm Springs' },
      'col-18': { text: 'West Sacramento' },
      'col-19': { text: 'Las Vegas' },
      'col-20': { text: 'Spring Hill' },
    },
  ],
}
